spring.application.name=gesinventario-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/gesinventario
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update